version: '3.7'

services:
  app:
    container_name: nodejs-api
    build:
      dockerfile: ./Dockerfile
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    command: sh -c "npm install && node server.js"
    #ports: 
    #  - "8080:8080"
    tty: true
    depends_on:
      - db
    volumes:
      - ./node:/app
    networks:
      - networknodemysql
    

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root    
    volumes:
      - ./mysql/data:/var/lib/mysql
      #- ./init:/docker-entrypoint-initdb.d
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - networknodemysql

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - "8080:80"
    depends_on:
      - app
    networks:
      - networknodemysql

networks:
  networknodemysql:
    driver: bridge